version: '3'
services:
  backend:
    build: backend/.
    ports:
      - "8000:8000"
    links:
      - mysql
      - rabbitmq
    depends_on:
      - mysql
      - rabbitmq
    volumes:
      - ./backend:/app
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3.11
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  frontend:
    image: node:14.17-alpine
    build: frontend/.
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: [ "npm", "start" ]
